### ISSUE TITLE
BUG: Fetching remote context not working

### ISSUE THREAD

**Issue by HelgeKrueger** [elsevierlabs-os/linked-data#10]
Remote "@context" is not properly supported, i.e. https not recognized. 

# How to reproduce

Create a file with content:

```json
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "actor": "https://other_domain/users/phoenix",
  "id": "https://other_domain/users/phoenix#likes/557",
  "object": "https://my_domain/activitypub/helge/id567",
  "type": "Like"
}
```

run `Linked-Data: Compact`

## Error messages:

> file:///home/helge/code/bovine/tests/data/https%3A/www.w3.org/ns/activitystreams. Detail: Unable to read file '/home/helge/code/bovine/tests/data/https:/www.w3.org/ns/activitystreams' (Error: Unable to resolve nonexistent file '/home/helge/code/bovine/tests/data/https:/www.w3.org/ns/activitystreams')

and

> Dereferencing a URL did not result in a valid JSON-LD object. Possible causes are an inaccessible URL perhaps due to a same-origin policy (ensure the server uses CORS if you are using client-side JavaScript), too many redirects, a non-JSON response, or more than one HTTP Link Header was provided for a remote context.

**Comment by RinkeHoekstra** [comment]
Ah, yes, that's not a bug, but an unfortunate error message. 

Fetching remote contexts works out-of-the-box with rdflib.js. All the extension is trying to do is to load contexts that look like strings as files. The error is thrown if this fails (in your case because the sting is a URL). However, the extension will continue processing the JSON-LD file. 

The reason you're not seeing anything happening is that you're compacting an already compacted file.

**Comment by RinkeHoekstra** [comment]
@HelgeKrueger this should now be a lot more robust since https://github.com/elsevierlabs-os/linked-data/releases/tag/v1.0.8 . 

The extension now uses the [Axios](https://axios-http.com/) library to prefetch the context: this should be more robust than the built-in mechanism of RDFLib (as it is less susceptible to CORS issues).
